# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: gcc:10.2


pipelines:
  default:
    - parallel:
        - step:
            name: Build and Run
            script:
               - apt-get update
               - apt-get install libeigen3-dev
               - apt-get install  libfftw3-bin libfftw3-long3 libfftw3-quad3 libfftw3-single3 libfftw3-dev  libfftw3-doc
               - apt-get install -y cmake
               - mkdir build
               - cd build 
               - cmake ..
               - make
               - cd phi4
               - ./phi4_new read_plateaux -p ../../tests/phi4  G2t_T32_L20_msq0-4.925000_msq1-4.850000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_bin100_merged_bin1000 -bin 1 jack
               - cd ../../tests/phi4 
               - bash script_check.sh
              
