# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: gcc:10.2

options:
  max-time: 3
pipelines:
  default:
    - parallel:
        - step:
            name: Build and Run
            script:
               - apt-get update
               - apt-get install libeigen3-dev
               - apt-get install  libfftw3-bin libfftw3-long3 libfftw3-quad3 libfftw3-single3 libfftw3-dev  libfftw3-doc
               - apt-get install -y cmake
               - apt-get install -y libgsl-dev
               - git submodule update --init --recursive
               - mkdir build
               - cd build 
               - cmake ..
               - make
               - cd phi4
               - ./phi4_new read_plateaux -p ../../tests/phi4  G2t_T48_L20_msq0-4.925000_msq1-4.850000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_bin40_merged_bin1000  -bin 1 jack
               - ./test ../../tests/phi4/jackknife/jack_G2t_T48_L20_msq0-4.925000_msq1-4.850000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0_reference ../../tests/phi4/jackknife/jack_G2t_T48_L20_msq0-4.925000_msq1-4.850000_l02.500000_l12.500000_mu5.000000_g0.000000_rep0
               
              
